pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [fthomas]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Build and Test (ubuntu-latest, 2.13.10, adopt-hotspot@17)
      - status-success=Build and Test (ubuntu-latest, 2.13.10, adopt-hotspot@11)
    actions:
      merge:
        method: squash
